### ISSUE TITLE
Different release in the npm registry

### ISSUE THREAD

**Issue by akoenig** [jonschlinkert/frep#4]
frep is nice. Thanks for putting it up.

Is it possible that there is a different release in the npm registry? Looks like that the version there has a missing lodash dependency. It is only declared as a dev dependency in the package.json. So the repo version with the tag 0.1.6 differs from the one which is in the registry.

``` javascript
  "devDependencies": {
    "chai": "~1.9.0",
    "mocha": "~1.17.1",
    "lodash": "~2.4.1",
    "underscore.string": "~2.3.3"
  }
```

Therefore

```
Error: Cannot find module 'lodash'
```

**Comment by jonschlinkert** [comment]
thanks! that's strange, I'll just fix it and do a new release. give me a minute...

**Comment by jonschlinkert** [comment]
k, should be fixed. let me know if you have any issues still. 

thanks again!

**Comment by akoenig** [comment]
Great! Works perfectly now. Thanks!

**Comment by jonschlinkert** [comment]
:+1:
