### ISSUE TITLE
Is there any posibility to replace string as is, without regex convertation?

### ISSUE THREAD

**Issue by vovayatsyuk** [jonschlinkert/frep#5]
The following rules cause frep to throw an error.

```
{
    pattern: "<comment><![CDATA[",
    replacement: ""
}
```

Produce the following error: 

```
Invalid regular expression: /<comment><![CDATA[/: Unterminated character class.
```

and 

```
{
    "<comment><![CDATA[": ""
}
```

Produces 

```
Invalid regular expression: /<comment><![CDATA[|patterns/: Unterminated character class.
```

**Comment by jonschlinkert** [comment]
I thought this was implemented... but I think I know what the cause is. I'll look into it. thanks

**Comment by jonschlinkert** [comment]
I just added this test, it passes as-is: https://github.com/jonschlinkert/frep/blob/7047e4b7edcbdd858716c7877bba1a39349ef562/test/strings.js

If the test isn't correct, maybe you can do a pr with the failing unit test and I'll get it passing. thx

**Comment by vovayatsyuk** [comment]
Yes, you are right. It works as expected. 

This issue appears when I use the gulp-frep plugin and pattern is

```
{
    pattern: "<comment><![CDATA[",
    replacement: ""
}
```

When I use the same pattern in frep itself, no errors where produced.

Stack trace:

```
Uncaught SyntaxError: Invalid regular expression: /<comment><![CDATA[/: Unterminated character class
      at new RegExp (<anonymous>)
      at Object.utils.buildRegexGroup (d:\www\dev\gulp-frep\node_modules\frep\lib\utils.js:27:10)
      at d:\www\dev\gulp-frep\node_modules\frep\index.js:28:27
      at Array.map (native)
      at Object.strWithArr (d:\www\dev\gulp-frep\node_modules\frep\index.js:26:41)
      at d:\www\dev\gulp-frep\test\test.js:65:38
```

**Comment by vovayatsyuk** [comment]
Should I create a unit test in gulp-frep repo for this issue?

**Comment by jonschlinkert** [comment]
sure, that works. thanks

**Comment by vovayatsyuk** [comment]
I'm closing this issue. 

It was related to old version of frep used in gulp-frep dependencies. Fixed in [gulp-frep pr](https://github.com/jonschlinkert/gulp-frep/pull/5)
